In [1]:
import numpy as np

In [26]:
A = np.array([1, 2, 2])

In [3]:
type([1, 2, 2])

list

In [4]:
type(A)

numpy.ndarray

In [5]:
A.shape

(3,)

In [6]:
B = np.array([[1, 2, 2], [1, 2, 3]])

In [7]:
B.shape

(2, 3)

In [8]:
C = np.zeros(shape=(100, 100, 100))

In [10]:
print(C)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [11]:
A = B

In [12]:
A

array([[1, 2, 2],
       [1, 2, 3]])

In [13]:
B

array([[1, 2, 2],
       [1, 2, 3]])

In [14]:
A+B

array([[2, 4, 4],
       [2, 4, 6]])

In [15]:
A*B

array([[1, 4, 4],
       [1, 4, 9]])

In [16]:
A/B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
A**2

array([[1, 4, 4],
       [1, 4, 9]])

In [19]:
A = {}

In [20]:
A["apple"] = "蘋果"

In [21]:
B = [1, 2, 3]

In [22]:
B[0]

1

In [23]:
C[0, 2, 8]

0.0

In [24]:
A["apple"]

'蘋果'

In [27]:
A[1:2]

array([2])