# 題目說明：
下面的作法可以製造一個大小為4*4，而元素值介在0~4之間的np array，

請複製下列程式碼，並依照題目說明對該array進行操作。

In [1]:
import numpy as np

In [2]:
a = np.random.randint(0, 5, size=(4, 4))

In [3]:
a

array([[4, 1, 0, 4],
       [0, 0, 0, 3],
       [3, 0, 2, 2],
       [3, 4, 4, 2]])

# 第一題--二值化：

二值化是我們在進行圖像處理時，時常使用的技巧。

關鍵在於把本來擁有各種數值的矩陣，變成只有兩個值。

（這樣會把彩色的圖變成黑白的噢，至於為什麼就請你自己查了ＸＤ）


# 問題來了：

請你把矩陣a裡面，大於0的值全部變成1，而0維持0。

提示：可以使用之前教過的for迴圈跟if。

進階：numpy有一個非常高明的技巧可以做到這個，

請你練習google看看把它找出來。

# 這可以用在哪裡：

某些助教之前在做漢字字型的自動生成研究時，

這是非常重要，可以改善結果的小技巧。

# 解答一： for 迴圈

In [4]:
# 這裡做不做都沒關係，只是為了後面方便，所以把a用c複製下來。
c = a

# 正式開始
for i in range(4):
    for j in range(4):
        if c[i][j] > 0:
            c[i][j] = 1
        else: 
            c[i][j] = 0

In [5]:
a

array([[1, 1, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 1],
       [1, 1, 1, 1]])

In [6]:
c

array([[1, 1, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 1],
       [1, 1, 1, 1]])

# 傳說中的大絕招： np.where


In [7]:
b = np.where(a>0, 1, 0)

In [8]:
b

array([[1, 1, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 1],
       [1, 1, 1, 1]])

# 說明：

這是numpy的一個小技巧。

np.where這個函式的用法大致上是： np.where(condition, x, y)，

滿足condition的部分會做x, 不滿足的會做y。

缺點是使用時很容易不小心寫錯出bug，要多練習。

# 進階挑戰第二題--GLCM：

GLCM是一種非常特別的矩陣，

在進行人工智慧的圖像辨識時，

可以當作圖片的某種「特徵」來處理。

做法大概是這樣的：


## 假裝你已經有了一個二值化的矩陣：

In [9]:
a = np.random.randint(0, 2, size=(4, 4))

In [10]:
a

array([[1, 0, 0, 0],
       [0, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1]])

最基本的GLCM會把兩兩一組數字的出現頻率記錄下來。

比如說(0, 0)在a矩陣出現的次數是3， (0, 1)是5， (1, 0)是3， (1, 1）是1，

那a的GLCM就會長這樣： [3, 5, 3, 1]

In [11]:
GLCM_a = np.array([3, 5, 3, 1])
GLCM_a

array([3, 5, 3, 1])

# 問題來了：

請你自己產生一個4*4的二值化矩陣，
然後寫一個函式把他的GLCM顯示出來。



# 這可以幹嘛：

某些助教前幾天好不容易搞定了一個用在研究上的進階GLCM寫法，

做夢都會夢到的那種。


# 解答一：陰魂不散的for迴圈

In [12]:
def GLCM(a):
    output = np.zeros(shape=(4, ))
    
    #(i, j)直接寫(4, 3)也可以，只是使用shape可以處理大小不固定的矩陣。
    # a.shape = [4, 4]
    for i in range(a.shape[0]):
        for j in range(a.shape[1]-1):
            if [a[i][j], a[i][j+1]] == [0, 0]:
                output[0] += 1
            
            elif [a[i][j], a[i][j+1]] == [0, 1]:
                output[1] += 1
            
            elif [a[i][j], a[i][j+1]] == [1, 0]:
                output[2] += 1
            
            elif [a[i][j], a[i][j+1]] == [1, 1]:
                output[3] += 1
                
    print (output)
            

In [13]:
GLCM(a)

[ 5.  1.  1.  5.]


#  解答二--黃助教的神乎其技：


In [14]:
def GLCM_ultra(a):
    output = np.zeros(shape=(4, ))

    b = a[:, :-1]
    c = a[:, 1:]
    
    one = np.ones(shape=(a.shape[0], a.shape[1]-1))
    
    not_b = one - b
    not_c = one - c
    
    #一些邏輯:
    # a and b = a*b
    # a or b = a*b - a+b
    # not a = 1 - a
    
    # (0, 0)
    # (not b) and (not c)
    output[0] = np.sum(not_b*not_c)
    
    #(0, 1)
    # (not a) and b
    output[1] = np.sum(not_b*c)
    
    #(1, 0)
    # a and (not b)
    output[2] = np.sum(b*not_c)
    
    #(1, 1)
    # a and b
    output[3] = np.sum(b*c)
    
    print(output)


In [15]:
GLCM_ultra(a)

[ 5.  1.  1.  5.]


# 看起來一樣，對嗎？

# 那為什麼要寫得這麼複雜呢？

因為numpy有個很重要的特色是「平行化運算」，

用for迴圈要算好幾百次的東西，用numpy的特殊寫法可以「一次」就算完。

上面寫法的特色，就在於都是「整個矩陣」地在處理，

會比用for迴圈一個元素一個元素慢慢比快很多。

# 用一個大一點的矩陣來比看看速度：

In [16]:
a_ultra = np.random.randint(0, 2, size=(256, 256))

In [17]:
import time

start = time.time()
GLCM(a_ultra)
end = time.time()

print()
print("花費時間： ", str(end-start)+"ms")

[ 16306.  16397.  16381.  16196.]

花費時間：  0.382612943649292ms


In [18]:
start = time.time()
GLCM_ultra(a_ultra)
end = time.time()

print()
print("花費時間： ", str(end-start)+"ms")

[ 16306.  16397.  16381.  16196.]

花費時間：  0.0068438053131103516ms


# 想想看，如果這是全台灣人的資料形成的，超級大矩陣。

# 平行化之後會快多少？